[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "mkdocs-navmodifier"
version = "0.1.0"
requires-python = ">=3.8"

[project.entry-points."mkdocs.plugins"]
navmodifier = "plugins.navmodifier:NavModifierPlugin"

[tool.setuptools.packages.find]
where = ["."]
include = ["plugins*"]
